dist:     xenial

addons:
  apt:
    packages:
    - libgl1-mesa-dev
    - qt5-default

language: cpp

os:
    - linux
    - osx

compiler:
    - gcc
    - clang

env:
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Debug GLIDENUI=On
    - TARGET_CPU=amd64 BUILD_CONFIGURATION=Release GLIDENUI=On
    # - TARGET_CPU=x86 BUILD_CONFIGURATION=Debug
    # - TARGET_CPU=x86 BUILD_CONFIGURATION=Release

jobs:
    exclude:
        - os:       osx
          compiler: gcc

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Debug

        - os:  osx
          env: TARGET_CPU=x86 BUILD_CONFIGURATION=Release

script:
    - src/getRevision.sh
    - cd projects/cmake
    - if [ "$TRAVIS_OS_NAME" = "osx" ]; then export GLIDENUI=Off; fi
    - cmake -DCMAKE_BUILD_TYPE=$BUILD_CONFIGURATION -DTARGET_CPU=$TARGET_CPU -DVEC4_OPT=On -DMUPENPLUSAPI=On -DMUPENPLUSAPI_GLIDENUI=$GLIDENUI ../../src/
    - cmake --build .
    - cd ../../
