#ifndef GLFUNCTIONS_H
#define GLFUNCTIONS_H

#ifdef OS_WINDOWS
#include <windows.h>
#elif defined(OS_LINUX)
//#define GL_GLEXT_PROTOTYPES
#include <winlnxdefs.h>
#endif

#ifdef EGL
#include <GL/glcorearb.h>
#else
#include <GL/gl.h>
#endif

#include <GL/glext.h>

#ifdef EGL
#define glBlendFunc g_glBlendFunc
#define glPixelStorei g_glPixelStorei
#define glClearColor g_glClearColor
#define glCullFace g_glCullFace
#define glDepthFunc g_glDepthFunc
#define glDepthMask g_glDepthMask
#define glDisable g_glDisable
#define glEnable g_glEnable
#define glPolygonOffset g_glPolygonOffset
#define glScissor g_glScissor
#define glViewport g_glViewport
#define glBindTexture g_glBindTexture
#define glTexImage2D g_glTexImage2D
#define glTexParameteri g_glTexParameteri
#define glGetIntegerv g_glGetIntegerv
#define glGetString g_glGetString
#define glReadPixels g_glReadPixels
#define glTexSubImage2D g_glTexSubImage2D
#define glDrawArrays g_glDrawArrays
#define glGetError g_glGetError
#define glDrawElements g_glDrawElements
#define glLineWidth g_glLineWidth
#define glClear g_glClear
#define glGetFloatv g_glGetFloatv
#define glDeleteTextures g_glDeleteTextures
#define glGenTextures g_glGenTextures
#define glTexParameterf g_glTexParameterf
#define glActiveTexture g_glActiveTexture
#define glBlendColor g_glBlendColor
#define glReadBuffer g_glReadBuffer

extern PFNGLBLENDFUNCPROC g_glBlendFunc;
extern PFNGLPIXELSTOREIPROC g_glPixelStorei;
extern PFNGLCLEARCOLORPROC g_glClearColor;
extern PFNGLCULLFACEPROC g_glCullFace;
extern PFNGLDEPTHFUNCPROC g_glDepthFunc;
extern PFNGLDEPTHMASKPROC g_glDepthMask;
extern PFNGLDISABLEPROC g_glDisable;
extern PFNGLENABLEPROC g_glEnable;
extern PFNGLPOLYGONOFFSETPROC g_glPolygonOffset;
extern PFNGLSCISSORPROC g_glScissor;
extern PFNGLVIEWPORTPROC g_glViewport;
extern PFNGLBINDTEXTUREPROC g_glBindTexture;
extern PFNGLTEXIMAGE2DPROC g_glTexImage2D;
extern PFNGLTEXPARAMETERIPROC g_glTexParameteri;
extern PFNGLGETINTEGERVPROC g_glGetIntegerv;
extern PFNGLGETSTRINGPROC g_glGetString;
extern PFNGLREADPIXELSPROC g_glReadPixels;
extern PFNGLTEXSUBIMAGE2DPROC g_glTexSubImage2D;
extern PFNGLDRAWARRAYSPROC g_glDrawArrays;
extern PFNGLGETERRORPROC g_glGetError;
extern PFNGLDRAWELEMENTSPROC g_glDrawElements;
extern PFNGLLINEWIDTHPROC g_glLineWidth;
extern PFNGLCLEARPROC g_glClear;
extern PFNGLGETFLOATVPROC g_glGetFloatv;
extern PFNGLDELETETEXTURESPROC g_glDeleteTextures;
extern PFNGLGENTEXTURESPROC g_glGenTextures;
extern PFNGLTEXPARAMETERFPROC g_glTexParameterf;
extern PFNGLACTIVETEXTUREPROC g_glActiveTexture;
extern PFNGLBLENDCOLORPROC g_glBlendColor;
extern PFNGLREADBUFFERPROC g_glReadBuffer;
#endif

#ifdef OS_WINDOWS
#define glActiveTexture g_glActiveTexture
#define glBlendColor g_glBlendColor

extern PFNGLACTIVETEXTUREPROC g_glActiveTexture;
extern PFNGLBLENDCOLORPROC g_glBlendColor;
#endif

#define glCreateShader g_glCreateShader
#define glCompileShader g_glCompileShader
#define glShaderSource g_glShaderSource
#define glCreateProgram g_glCreateProgram
#define glAttachShader g_glAttachShader
#define glLinkProgram g_glLinkProgram
#define glUseProgram g_glUseProgram
#define glGetUniformLocation g_glGetUniformLocation
#define glUniform1i g_glUniform1i
#define glUniform1f g_glUniform1f
#define glUniform2f g_glUniform2f
#define glUniform2i g_glUniform2i
#define glUniform4i  g_glUniform4i

#define glUniform4f g_glUniform4f
#define glUniform3fv g_glUniform3fv
#define glUniform4fv g_glUniform4fv
#define glDetachShader g_glDetachShader
#define glDeleteShader g_glDeleteShader
#define glDeleteProgram g_glDeleteProgram
#define glGetProgramInfoLog g_glGetProgramInfoLog
#define glGetShaderInfoLog g_glGetShaderInfoLog
#define glGetShaderiv g_glGetShaderiv
#define glGetProgramiv g_glGetProgramiv

#define glEnableVertexAttribArray g_glEnableVertexAttribArray
#define glDisableVertexAttribArray g_glDisableVertexAttribArray
#define glVertexAttribPointer g_glVertexAttribPointer
#define glBindAttribLocation g_glBindAttribLocation
#define glVertexAttrib4f g_glVertexAttrib4f
#define glVertexAttrib4fv g_glVertexAttrib4fv

#define glDepthRangef g_glDepthRangef
#define glClearDepthf g_glClearDepthf

#define glDrawBuffers g_glDrawBuffers
#define glGenFramebuffers g_glGenFramebuffers
#define glBindFramebuffer g_glBindFramebuffer
#define glDeleteFramebuffers g_glDeleteFramebuffers
#define glFramebufferTexture2D g_glFramebufferTexture2D
#define glTexImage2DMultisample g_glTexImage2DMultisample
#define glTexStorage2DMultisample g_glTexStorage2DMultisample
#define glGenRenderbuffers g_glGenRenderbuffers
#define glBindRenderbuffer g_glBindRenderbuffer
#define glRenderbufferStorage g_glRenderbufferStorage
#define glDeleteRenderbuffers g_glDeleteRenderbuffers
#define glFramebufferRenderbuffer g_glFramebufferRenderbuffer
#define glCheckFramebufferStatus g_glCheckFramebufferStatus
#define glBlitFramebuffer g_glBlitFramebuffer
#define glGenVertexArrays g_glGenVertexArrays
#define glBindVertexArray g_glBindVertexArray
#define glDeleteVertexArrays g_glDeleteVertexArrays;
#define glGenBuffers g_glGenBuffers
#define glBindBuffer g_glBindBuffer
#define glBufferData g_glBufferData
#define glMapBuffer g_glMapBuffer
#define glMapBufferRange g_glMapBufferRange
#define glUnmapBuffer g_glUnmapBuffer
#define glDeleteBuffers g_glDeleteBuffers
#define glBindImageTexture g_glBindImageTexture
#define glMemoryBarrier g_glMemoryBarrier
#define glGetStringi g_glGetStringi
#define glInvalidateFramebuffer g_glInvalidateFramebuffer
#define glBufferStorage g_glBufferStorage
#define glFenceSync g_glFenceSync
#define glClientWaitSync g_glClientWaitSync
#define glDeleteSync g_glDeleteSync

#define glGetUniformBlockIndex g_glGetUniformBlockIndex
#define glUniformBlockBinding g_glUniformBlockBinding
#define glGetActiveUniformBlockiv g_glGetActiveUniformBlockiv
#define glGetUniformIndices g_glGetUniformIndices
#define glGetActiveUniformsiv g_glGetActiveUniformsiv
#define glBindBufferBase g_glBindBufferBase
#define glBufferSubData g_glBufferSubData

#define glGetProgramBinary g_glGetProgramBinary
#define glProgramBinary g_glProgramBinary
#define glProgramParameteri g_glProgramParameteri

#define glTexStorage2D g_glTexStorage2D
#define glTextureStorage2D g_glTextureStorage2D
#define glTextureSubImage2D g_glTextureSubImage2D
#define glTextureStorage2DMultisample g_glTextureStorage2DMultisample
#define glTextureParameteri g_glTextureParameteri
#define glTextureParameterf g_glTextureParameterf
#define glCreateTextures g_glCreateTextures
#define glCreateBuffers g_glCreateBuffers
#define glCreateFramebuffers g_glCreateFramebuffers
#define glNamedFramebufferTexture g_glNamedFramebufferTexture
#define glDrawElementsBaseVertex g_glDrawElementsBaseVertex

extern PFNGLCREATESHADERPROC g_glCreateShader;
extern PFNGLCOMPILESHADERPROC g_glCompileShader;
extern PFNGLSHADERSOURCEPROC g_glShaderSource;
extern PFNGLCREATEPROGRAMPROC g_glCreateProgram;
extern PFNGLATTACHSHADERPROC g_glAttachShader;
extern PFNGLLINKPROGRAMPROC g_glLinkProgram;
extern PFNGLUSEPROGRAMPROC g_glUseProgram;
extern PFNGLGETUNIFORMLOCATIONPROC g_glGetUniformLocation;
extern PFNGLUNIFORM1IPROC g_glUniform1i;
extern PFNGLUNIFORM1FPROC g_glUniform1f;
extern PFNGLUNIFORM2FPROC g_glUniform2f;
extern PFNGLUNIFORM2IPROC g_glUniform2i;
extern PFNGLUNIFORM4IPROC g_glUniform4i;

extern PFNGLUNIFORM4FPROC g_glUniform4f;
extern PFNGLUNIFORM3FVPROC g_glUniform3fv;
extern PFNGLUNIFORM4FVPROC g_glUniform4fv;
extern PFNGLDETACHSHADERPROC g_glDetachShader;
extern PFNGLDELETESHADERPROC g_glDeleteShader;
extern PFNGLDELETEPROGRAMPROC g_glDeleteProgram;
extern PFNGLGETPROGRAMINFOLOGPROC g_glGetProgramInfoLog;
extern PFNGLGETSHADERINFOLOGPROC g_glGetShaderInfoLog;
extern PFNGLGETSHADERIVPROC g_glGetShaderiv;
extern PFNGLGETPROGRAMIVPROC g_glGetProgramiv;

extern PFNGLENABLEVERTEXATTRIBARRAYPROC g_glEnableVertexAttribArray;
extern PFNGLDISABLEVERTEXATTRIBARRAYPROC g_glDisableVertexAttribArray;
extern PFNGLVERTEXATTRIBPOINTERPROC g_glVertexAttribPointer;
extern PFNGLBINDATTRIBLOCATIONPROC g_glBindAttribLocation;
extern PFNGLVERTEXATTRIB4FPROC g_glVertexAttrib4f;
extern PFNGLVERTEXATTRIB4FVPROC g_glVertexAttrib4fv;

extern PFNGLDEPTHRANGEFPROC g_glDepthRangef;
extern PFNGLCLEARDEPTHFPROC g_glClearDepthf;

extern PFNGLDRAWBUFFERSPROC g_glDrawBuffers;
extern PFNGLGENFRAMEBUFFERSPROC g_glGenFramebuffers;
extern PFNGLBINDFRAMEBUFFERPROC g_glBindFramebuffer;
extern PFNGLDELETEFRAMEBUFFERSPROC g_glDeleteFramebuffers;
extern PFNGLFRAMEBUFFERTEXTURE2DPROC g_glFramebufferTexture2D;
extern PFNGLTEXIMAGE2DMULTISAMPLEPROC g_glTexImage2DMultisample;
extern PFNGLTEXSTORAGE2DMULTISAMPLEPROC g_glTexStorage2DMultisample;
extern PFNGLGENRENDERBUFFERSPROC g_glGenRenderbuffers;
extern PFNGLBINDRENDERBUFFERPROC g_glBindRenderbuffer;
extern PFNGLRENDERBUFFERSTORAGEPROC g_glRenderbufferStorage;
extern PFNGLDELETERENDERBUFFERSPROC g_glDeleteRenderbuffers;
extern PFNGLFRAMEBUFFERRENDERBUFFERPROC g_glFramebufferRenderbuffer;
extern PFNGLCHECKFRAMEBUFFERSTATUSPROC g_glCheckFramebufferStatus;
extern PFNGLBLITFRAMEBUFFERPROC g_glBlitFramebuffer;
extern PFNGLGENVERTEXARRAYSPROC g_glGenVertexArrays;
extern PFNGLBINDVERTEXARRAYPROC g_glBindVertexArray;
extern PFNGLDELETEVERTEXARRAYSPROC g_glDeleteVertexArrays;
extern PFNGLGENBUFFERSPROC g_glGenBuffers;
extern PFNGLBINDBUFFERPROC g_glBindBuffer;
extern PFNGLBUFFERDATAPROC g_glBufferData;
extern PFNGLMAPBUFFERPROC g_glMapBuffer;
extern PFNGLMAPBUFFERRANGEPROC g_glMapBufferRange;
extern PFNGLUNMAPBUFFERPROC g_glUnmapBuffer;
extern PFNGLDELETEBUFFERSPROC g_glDeleteBuffers;
extern PFNGLBINDIMAGETEXTUREPROC g_glBindImageTexture;
extern PFNGLMEMORYBARRIERPROC g_glMemoryBarrier;
extern PFNGLGETSTRINGIPROC g_glGetStringi;
extern PFNGLINVALIDATEFRAMEBUFFERPROC g_glInvalidateFramebuffer;
extern PFNGLBUFFERSTORAGEPROC g_glBufferStorage;
extern PFNGLFENCESYNCPROC g_glFenceSync;
extern PFNGLCLIENTWAITSYNCPROC g_glClientWaitSync;
extern PFNGLDELETESYNCPROC g_glDeleteSync;

extern PFNGLGETUNIFORMBLOCKINDEXPROC g_glGetUniformBlockIndex;
extern PFNGLUNIFORMBLOCKBINDINGPROC g_glUniformBlockBinding;
extern PFNGLGETACTIVEUNIFORMBLOCKIVPROC g_glGetActiveUniformBlockiv;
extern PFNGLGETUNIFORMINDICESPROC g_glGetUniformIndices;
extern PFNGLGETACTIVEUNIFORMSIVPROC g_glGetActiveUniformsiv;
extern PFNGLBINDBUFFERBASEPROC g_glBindBufferBase;
extern PFNGLBUFFERSUBDATAPROC g_glBufferSubData;

extern PFNGLGETPROGRAMBINARYPROC g_glGetProgramBinary;
extern PFNGLPROGRAMBINARYPROC g_glProgramBinary;
extern PFNGLPROGRAMPARAMETERIPROC g_glProgramParameteri;

extern PFNGLTEXSTORAGE2DPROC g_glTexStorage2D;
extern PFNGLTEXTURESTORAGE2DPROC g_glTextureStorage2D;
extern PFNGLTEXTURESUBIMAGE2DPROC g_glTextureSubImage2D;
extern PFNGLTEXTURESTORAGE2DMULTISAMPLEEXTPROC g_glTextureStorage2DMultisample;
extern PFNGLTEXTUREPARAMETERIPROC g_glTextureParameteri;
extern PFNGLTEXTUREPARAMETERFPROC g_glTextureParameterf;
extern PFNGLCREATETEXTURESPROC g_glCreateTextures;
extern PFNGLCREATEBUFFERSPROC g_glCreateBuffers;
extern PFNGLCREATEFRAMEBUFFERSPROC g_glCreateFramebuffers;
extern PFNGLNAMEDFRAMEBUFFERTEXTUREPROC g_glNamedFramebufferTexture;
extern PFNGLDRAWELEMENTSBASEVERTEXPROC g_glDrawElementsBaseVertex;

void initGLFunctions();

#endif // GLFUNCTIONS_H
