//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GLideNUI.rc
//
#define ID_SAVE                         3
#define ID_SAVECLOSE                    4
#define ID_RESTORE_DEFAULTS             5
#define IDD_ABOUT                       101
#define IDI_APPICON                     102
#define IDD_TAB_ABOUT                   103
#define IDD_TAB_FUNDERS                 104
#define IDD_TAB_CREDITS                 105
#define IDD_TAB_CONTRIBUTORS            106
#define IDD_CONFIG                      107
#define IDD_TAB_VIDEO                   108
#define IDD_TAB_OVERSCAN                109
#define IDD_TAB_EMULATION               110
#define IDD_TAB_FRAME_BUFFER            111
#define IDD_TAB_TEXTURE_ENHANCEMENT     112
#define IDD_TAB_OSD                     113
#define IDD_TAB_DEBUG                   114
#define IDI_ICON_INFO                   115
#define IDD_TAB_DEBUG2                  115
#define IDI_ICON_WARNING                116
#define IDI_OSD_TOP_LEFT                117
#define IDI_OSD_TOP                     118
#define IDI_OSD_TOP_RIGHT               119
#define IDI_OSD_LEFT                    120
#define IDI_OSD_RIGHT                   121
#define IDI_OSD_BOTTOM_LEFT             122
#define IDI_OSD_BOTTOM                  123
#define IDI_OSD_BOTTOM_RIGHT            124
#define IDD_INPUT_DIALOG                128
#define IDD_TAB_ANGLE                   129
#define IDR_RCDATA_CUSTOM_DEFAULT       133
#define IDR_RCDATA_DEFAULT              134
#define IDC_ABOUT_TITLE                 1001
#define IDC_TABS                        1002
#define IDC_CONTRIBUTORS                1003
#define IDC_FUNDERS                     1004
#define IDC_FUNDERS_LIST                1005
#define IDC_ORKIN                       1006
#define IDC_YONGZH                      1007
#define IDC_HIROSHI                     1008
#define IDC_ZIGGY                       1009
#define IDC_CMB_FULL_SCREEN_RES         1010
#define IDC_CMB_REFRESH_RATE            1011
#define IDC_CMB_WINDOWED_RESOLUTION     1012
#define IDC_CMB_ASPECT_RATIO            1013
#define IDC_CHK_VERTICAL_SYNC           1014
#define IDC_CHK_THREADED_VIDEO          1015
#define IDC_CHK_OVERSCAN                1016
#define IDC_TAB_OVERSCAN                1017
#define IDC_NOAA_RADIO                  1018
#define IDC_FXAA_RADIO                  1019
#define IDC_MSAA_RADIO                  1020
#define IDC_ALIASING_SLIDER             1021
#define IDC_ALIASING_LABEL              1022
#define IDC_AA_INFO_ICON                1023
#define IDC_ANISOTROPIC_SLIDER          1024
#define IDC_ANISOTROPIC_LABEL           1025
#define IDC_BILINEAR_STANDARD           1026
#define IDC_BILINEAR_3POINT             1027
#define IDC_OVERSCAN_LEFT_TXT           1030
#define IDC_OVERSCAN_LEFT_SPIN          1031
#define IDC_OVERSCAN_RIGHT_TXT          1032
#define IDC_OVERSCAN_RIGHT_SPIN         1033
#define IDC_OVERSCAN_TOP_TXT            1034
#define IDC_OVERSCAN_TOP_SPIN           1035
#define IDC_OVERSCAN_BOTTOM_TXT         1036
#define IDC_OVERSCAN_BOTTOM_SPIN        1037
#define IDC_CHK_USE_PER_GAME            1038
#define IDC_CHK_N64_STYLE_MIP_MAPPING   1039
#define IDC_CHK_HWLIGHTING              1040
#define IDC_CHK_PIXEL_COVERAGE          1041
#define IDC_CHK_SHADERS_STORAGE         1042
#define IDC_FACTOR0X_RADIO              1043
#define IDC_FACTOR1X_RADIO              1044
#define IDC_FACTORXX_RADIO              1045
#define IDC_N64_RES_MULTIPLER_TXT       1046
#define IDC_N64_RES_MULTIPLER_SPIN      1047
#define IDC_CHK_GAMMA_CORRECTION        1048
#define IDC_GAMMA_VALUE                 1049
#define IDC_GAMMA_SPIN                  1050
#define IDC_GAMMA_ICON                  1051
#define IDC_GAMMA_INFO                  1052
#define IDC_CMB_NATIVE_RES_2D           1053
#define IDC_CHK_HALOS_REMOVAL           1054
#define IDC_FIXTEXRECT_SMART            1055
#define IDC_FIXTEXRECT_FORCE            1056
#define IDC_FIXTEXRECT_NEVER            1057
#define IDC_BGMODE_ONEPIECE             1058
#define IDC_BGMODE_STRIPPED             1059
#define IDC_CHK_ENABLE_FRAMEBUFFER      1060
#define IDC_EMULATE_FB_ICON             1061
#define IDC_CHK_COPY_AUX_BUFFERS        1062
#define IDC_CMB_FRAMEBUFFER_SWAP        1063
#define IDC_CHK_FB_INFO_ENABLE          1064
#define IDC_CHK_READ_COLOR_CHUNK        1065
#define IDC_CHK_READ_DEPTH_CHUNK        1066
#define IDC_CMB_COPY_COLOR_BUFFER       1067
#define IDC_CMB_COPY_DEPTH_BUFFER       1068
#define IDC_CMB_N64_DEPTH_COMPARE       1069
#define IDC_CHK_FORCE_DEPTH_BUFFER_CLEAR 1070
#define IDC_CHK_RENDER_FRAMEBUFFER      1071
#define IDC_CHK_COPY_DEPTH_TO_MAIN_DEPTH_BUFFER 1072
#define IDC_CMB_FILTER                  1073
#define IDC_CMB_ENHANCEMENT             1074
#define IDC_CHK_DEPOSTERIZE             1075
#define IDC_CHK_DECREASE_COLOR          1075
#define IDC_CHK_IGNORE_BACKGROUNDS      1076
#define IDC_CHK_ENHANCED_TEX_FILE_STORAGE 1077
#define IDC_CHK_TEXTURE_PACK            1078
#define IDC_TEX_PACK_PATH_STATIC        1079
#define IDC_TEX_PACK_PATH_EDIT          1080
#define IDC_TEX_PACK_PATH_BTN           1081
#define IDC_TEX_CACHE_PATH_STATIC       1082
#define IDC_TEX_CACHE_PATH_EDIT         1083
#define IDC_TEX_CACHE_PATH_BTN          1084
#define IDC_TEX_DUMP_PATH_STATIC        1085
#define IDC_TEX_DUMP_PATH_EDIT          1086
#define IDC_TEX_DUMP_PATH_BTN           1087
#define IDC_CHK_ALPHA_CHANNEL           1088
#define IDC_CHK_ALTERNATIVE_CRC         1089
#define IDC_CHK_HIRES_TEX_FILESTORAGE   1090
#define IDC_TEXTURE_FILTER_CACHE_STATIC 1093
#define IDC_TEXTURE_FILTER_CACHE_EDIT   1094
#define IDC_TEXTURE_FILTER_CACHE_SPIN   1095
#define IDC_CHK_SAVE_TEXTURE_CACHE      1096
#define IDC_CHK_COMPRESS_CACHE          1097
#define IDC_CHK_FORCE_16BPP             1098
#define IDC_OSD_TOP_LEFT                1099
#define IDC_OSD_TOP                     1100
#define IDC_OSD_TOP_RIGHT               1101
#define IDC_OSD_CENTER_LEFT             1102
#define IDC_OSD_CENTER                  1103
#define IDC_OSD_CENTER_RIGHT            1104
#define IDC_OSD_BOTTOM_LEFT             1105
#define IDC_OSD_BOTTOM                  1106
#define IDC_OSD_BOTTOM_RIGHT            1107
#define IDC_CHK_FPS                     1108
#define IDC_CHK_VIS                     1109
#define IDC_CHK_PERCENT                 1110
#define IDC_INTERNAL_RESOLUTION         1111
#define IDC_RENDERING_RESOLUTION        1112
#define IDC_FONTS                       1113
#define IDC_FONT_SIZE_TXT               1114
#define IDC_FONT_SIZE_SPIN              1115
#define IDC_OSD_COLOR                   1116
#define IDC_OSD_PREVIEW                 1117
#define IDC_CHK_DUMP_LOW                1118
#define IDC_RENDERING_RESOLUTION2       1119
#define IDC_STATISTICS                  1120
#define IDC_CHK_DUMP_NORMAL             1121
#define IDC_CHK_DUMP_DETAIL             1122
#define IDC_SERGEY                      1123
#define IDC_OLIVIER                     1124
#define IDC_RYAN                        1125
#define IDC_ROLE1                       1126
#define IDC_TXT_DEVELOPER               1127
#define IDC_ROLE2                       1128
#define IDC_TXT_BETA_TESTER             1129
#define IDC_ROLE3                       1130
#define IDC_TXT_GUI_DESIGNER            1131
#define IDC_ABOUT_ICON                  1132
#define IDC_GAME_PROFILE                1133
#define IDC_SAVE_SETTINGS_STATIC        1134
#define IDC_USE_PROFILE                 1135
#define IDC_SETTINGS_PROFILE_STATIC     1136
#define IDC_PROFILE                     1137
#define IDC_REMOVE_PROFILE              1138
#define IDC_GAME_PROFILE_NAME           1139
#define IDC_AA_INFO                     1140
#define IDC_AA_GROUP                    1141
#define IDC_FILTERING_GROUP             1142
#define IDC_VIDEO_GROUP                 1143
#define IDC_ANISOTROPIC                 1144
#define IDC_BILINEAR                    1145
#define IDC_ANISOTROPIC_OFF             1146
#define IDC_ANISOTROPIC_HIGH            1147
#define IDC_AA_OFF                      1148
#define IDC_AA_HIGH                     1149
#define IDC_DITHERING_GROUP             1150
#define IDC_CHK_5BIT_QUANTIZATION       1151
#define IDC_CHK_APPLY_TO_OUTPUT         1152
#define IDC_CHK_HIRES_NOISE             1153
#define IDC_CMB_PATTERN                 1154
#define IDC_CMB_LANGUAGE                1155
#define IDC_PATTERN                     1156
#define IDC_INPUT                       1157
#define IDC_INFO                        1158
#define IDC_TXT_FULL_SCREEN_RES         1159
#define IDC_TXT_REFRESH_RATE            1160
#define IDC_TXT_WINDOWED_RESOLUTION     1161
#define IDC_TXT_ASPECT_RATIO            1162
#define IDC_LANGUAGE                    1163
#define IDC_INTERNAL_RES_GROUP          1164
#define IDC_GAMMA_GROUP                 1165
#define IDC_2D_ELEMENTS_GROUP           1166
#define IDC_TXT_FIXBLACK_LINES          1167
#define IDC_RENDER_2D_ELEMENTS          1168
#define IDC_TXT_BACKGROUND_RENDERING    1169
#define IDC_TXT_FRAMEBUFFER_SWAP        1170
#define IDC_TXT_COPY_COLOR_BUFFER       1171
#define IDC_TXT_COPY_DEPTH_BUFFER       1172
#define IDC_TXT_N64_DEPTH_COMPARE       1173
#define IDC_FRAME_BUFFER_INFO           1174
#define IDC_TXT_N64_TEXTURE             1175
#define IDC_TXT_TEXTURE_FILTER          1176
#define IDC_TXT_ENHANCEMENT             1177
#define IDC_POSITION                    1178
#define IDC_FONT                        1179
#define IDC_TXT_SIZE                    1180
#define IDC_PX                          1181
#define IDC_COLOR                       1182
#define IDC_TXT_NEW_GEN                 1183
#define IDC_TXT_AUTHORS                 1184
#define IDC_TXT_AUTHOR_GLN64            1185
#define IDC_TXT_                        1186
#define IDC_RADIO_DIRECT3D              1186
#define IDC_TXT_AUTHOR_GLES2N64         1187
#define IDC_RENDERER                    1187
#define IDC_TXT_AUTHOR_GLIDEHQ          1188
#define IDC_CHECK_ENABLE_FRAGMENT_DEPTH_WRITE 1188
#define IDC_TXT_AUTHOR_Z64              1189
#define IDC_RADIO_VULKAN                1189
#define IDC_CHECK_DX11_TO_12            1190
#define IDC_CHECK_DIRECT_COMPOSITION    1190

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        135
#define _APS_NEXT_COMMAND_VALUE         40002
#define _APS_NEXT_CONTROL_VALUE         1191
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
